const emojis = [
  ":grinning:",
  ":smiley:",
  ":smile:",
  ":grin:",
  ":heart_eyes:",
  ":star-struck:",
  ":relaxed:",
  ":partying_face:",
  ":smiley_cat:",
  ":smile_cat:",
  ":heart_eyes_cat:",
  ":clap:",
  ":raised_hands:",
  ":heart_hands:",
  ":pray:",
  ":dancer:",
  ":man_dancing:",
  ":men-with-bunny-ears-partying:",
  ":women-with-bunny-ears-partying:",
  ":rocket:",
  ":star:",
  ":star2:",
  ":zap:",
  ":fire:",
  ":sparkles:",
  ":tada:",
  ":confetti_ball:",
  ":magic_wand:",
  ":crown:",
  ":tophat:",
  ":high_brightness:",
];

exports.emojis = emojis;